--Criando database
CREATE DATABASE project_manager WITH ENCODING 'UTF8' LC_COLLATE='Portuguese_Brazil.1252' LC_CTYPE='Portuguese_Brazil.1252';

\c project_manager

--Criando usuário da aplicação
CREATE USER pmadmin WITH ENCRYPTED PASSWORD 'pmadmin2021';

--Dando Permissões para o usuário
GRANT ALL PRIVILEGES ON DATABASE project_manager TO pmadmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pmadmin;

CREATE TABLE STATUS_TAREFA_DESC (
STATUS_ID INT PRIMARY KEY,
STATUS_DESC VARCHAR (20) NOT NULL
);

CREATE TABLE COD_TIPO_DESC (
COD_TIPO_SIGLA CHAR (1) PRIMARY KEY,
COD_TIPO_DESC VARCHAR (20) NOT NULL
);

CREATE TABLE AVALIACAO_DESC (
AVAL_ID SERIAL PRIMARY KEY,
AVAL_TIPO VARCHAR (2) NOT NULL UNIQUE,
AVAL_DESC VARCHAR (25) NOT NULL
);

CREATE TABLE LIB_SIGLAS_DESC (
LIB_TIPO CHAR(1) PRIMARY KEY,
LIB_DESC VARCHAR (20)
);

CREATE TABLE PERFIL_DESC (
PERFIL_ID SERIAL PRIMARY KEY,
PERFIL_NOME VARCHAR (20) NOT NULL UNIQUE,
PERFIL_DESC VARCHAR (5000) NOT NULL
);

------------------ENTIDADES PRINCIPAIS------------------

CREATE TABLE UNIDADE_APLIC (
UNI_APLIC_ID SERIAL PRIMARY KEY,
UNI_NOME VARCHAR (40) NOT NULL UNIQUE,
UNI_CEP VARCHAR (8) NOT NULL,
UNI_PAIS VARCHAR (25) NOT NULL,
UNI_ESTADO VARCHAR (25) NOT NULL,
UNI_CIDADE VARCHAR (25) NOT NULL,
UNI_ENDERECO VARCHAR (50) NOT NULL UNIQUE,
UNI_NUM INT NOT NULL
);

CREATE TABLE ESCOLA_APLIC (
ESC_APLIC_ID SERIAL PRIMARY KEY,
ESC_NOME VARCHAR (50) NOT NULL UNIQUE,
ESC_CNPJ VARCHAR (14) NOT NULL UNIQUE,
DIR_FUND_NOME VARCHAR (35) NOT NULL UNIQUE,
DIR_FUND_EMAIL VARCHAR (25) NOT NULL,
DIR_FUND_TELEFONE VARCHAR (60) NOT NULL,
DIR_FUND_CPF VARCHAR (11) NOT NULL UNIQUE,
DIR_FUND_DT_NASC DATE NOT NULL,
DIR_FUND_DT_NASC VARCHAR(100)
);

CREATE TABLE CURSO_APLIC (
CUR_APLIC_ID SERIAL PRIMARY KEY,
CUR_COD VARCHAR(10) NOT NULL,
CUR_NOME VARCHAR (40) NOT NULL,
CUR_CORD VARCHAR (30) NOT NULL
);

CREATE TABLE DISCIPLINA_APLIC (
DISC_APLIC_ID SERIAL PRIMARY KEY,
DISC_NOME VARCHAR (40) NOT NULL,
DISC_DESCRICAO VARCHAR (250),
DISC_CODIGO VARCHAR (10)
);

CREATE TABLE CLASSE_APLIC (
CLAS_APLIC_ID SERIAL PRIMARY KEY,
CLAS_NOME VARCHAR (60) NOT NULL,
CLAS_COD VARCHAR (10) NOT NULL,
CLAS_DATA_CRIACAO DATE NOT NULL,
CLAS_PERIODO INT NOT NULL,
CLAS_SEMESTRE INT NOT NULL,
CLAS_ANO INT NOT NULL
);

CREATE TABLE USUARIO_APLIC (
USU_APLIC_ID SERIAL PRIMARY KEY,
USU_NOME VARCHAR (50) NOT NULL,
USU_EMAIL VARCHAR (55) NOT NULL UNIQUE,
USU_NASC DATE NOT NULL,
USU_REGISTRO VARCHAR (10) NOT NULL,
USU_CPF VARCHAR (11) NOT NULL UNIQUE,
USU_SENHA VARCHAR (100) NOT NULL,
USU_ATIVO CHAR(1) NOT NULL,
USU_CRIACAO TIMESTAMP NOT NULL,
USU_ULTIMO_ACESSO TIMESTAMP,
USU_TENTATIVAS INT NOT NULL
);

CREATE TABLE TRABALHO_APLIC (
TRAB_APLIC_ID SERIAL PRIMARY KEY,
TRAB_NOME VARCHAR (75) NOT NULL,
TRAB_PROFESSOR INT NOT NULL,
TRAB_DESCRICAO VARCHAR (500),
TRAB_CRIACAO DATE NOT NULL,
TRAB_ENTREGA DATE NOT NULL,
FOREIGN KEY (TRAB_PROFESSOR) REFERENCES USUARIO_APLIC(USU_APLIC_ID)
);

CREATE TABLE GRUPO_APLIC (
GRUPO_APLIC_ID SERIAL PRIMARY KEY,
GRUPO_NOME VARCHAR (60) NOT NULL,
GRUPO_USU_ID INT,
GRUPO_USU_LIDER CHAR (1),
GRUPO_ID INT,
FOREIGN KEY (GRUPO_USU_ID) REFERENCES USUARIO_APLIC(USU_APLIC_ID)
);

CREATE TABLE TAREFA_APLIC (
TAR_APLIC_ID SERIAL PRIMARY KEY,
TAR_NOME VARCHAR (50) NOT NULL,
TAR_DESC VARCHAR (250) NOT NULL,
TAR_RESP_ID INT NOT NULL,
TAR_USU_CRIADOR INT NOT NULL,
TAR_INI DATE,
TAR_FIM TIMESTAMP NOT NULL,
TAR_STATUS INT NOT NULL,
FOREIGN KEY (TAR_RESP_ID) REFERENCES USUARIO_APLIC(USU_APLIC_ID),
FOREIGN KEY (TAR_USU_CRIADOR) REFERENCES USUARIO_APLIC(USU_APLIC_ID),
FOREIGN KEY (TAR_STATUS) REFERENCES STATUS_TAREFA_DESC(STATUS_ID)
);

CREATE TABLE CODIGOS_APLIC (
CODIGOS_APLIC_ID SERIAL PRIMARY KEY,
COD_TIPO_DESC CHAR(1) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
DT_GERACAO DATE NOT NULL,
ATIVO CHAR(1) NOT NULL,
USU_EMAIL VARCHAR(80),
FOREIGN KEY (COD_TIPO_DESC) REFERENCES COD_TIPO_DESC(COD_TIPO_SIGLA)
);

CREATE TABLE LIBERA_APLIC (
LIBERA_APLIC_ID SERIAL PRIMARY KEY,
RELACAO_CLASSE_ID INT NOT NULL,
LIB_CPF VARCHAR (11) NOT NULL,
LIB_TIPO CHAR (1),
CODIGOS_ID INT NOT NULL,
FOREIGN KEY (RELACAO_CLASSE_ID) REFERENCES RELACAO_CLASSE(RELACAO_CLASSE_ID),
FOREIGN KEY (LIB_CPF) REFERENCES USUARIO_APLIC(USU_CPF),
FOREIGN KEY (LIB_TIPO) REFERENCES LIB_SIGLAS_DESC(LIB_TIPO),
FOREIGN KEY (CODIGOS_ID) REFERENCES CODIGOS_APLIC(CODIGOS_APLIC_ID)
);

---------------TABELAS DE RELACIONAMENTO-----------------

CREATE TABLE RELACAO_CLASSE (
RELACAO_CLASSE_ID SERIAL PRIMARY KEY,
ESC_ID INT NOT NULL,
UNI_ID INT,
CUR_ID INT,
DISC_ID INT,
CLAS_ID INT,
DT_REGISTRO TIMESTAMP,
FOREIGN KEY (ESC_ID) REFERENCES ESCOLA_APLIC(ESC_APLIC_ID),
FOREIGN KEY (UNI_ID) REFERENCES UNIDADE_APLIC(UNI_APLIC_ID),
FOREIGN KEY (CUR_ID) REFERENCES CURSO_APLIC(CUR_APLIC_ID),
FOREIGN KEY (DISC_ID) REFERENCES DISCIPLINA_APLIC(DISC_APLIC_ID),
FOREIGN KEY (CLAS_ID) REFERENCES CLASSE_APLIC(CLAS_APLIC_ID)
);

CREATE TABLE RELACAO_ACESSO (
RELACAO_ACESSO_ID SERIAL PRIMARY KEY,
RELACAO_CLASSE_ID INT NOT NULL,
USU_SOLICT_ID INT NOT NULL,
USU_ID INT NOT NULL,
ACES CHAR (1) NOT NULL,
DT_REGISTRO DATE NOT NULL,
DT_VENCIMENTO DATE,
FOREIGN KEY (RELACAO_CLASSE_ID) REFERENCES RELACAO_CLASSE(RELACAO_CLASSE_ID),
FOREIGN KEY (USU_ID) REFERENCES USUARIO_APLIC(USU_APLIC_ID),
FOREIGN KEY (USU_SOLICT_ID) REFERENCES USUARIO_APLIC(USU_APLIC_ID)
);

CREATE TABLE RELACAO_TRAB (
RELACAO_TRAB_ID SERIAL PRIMARY KEY,
RELACAO_CLASSE_ID INT NOT NULL,
TRAB_ID INT NOT NULL,
GRUPO_ID INT,
TAR_ID INT,
FOREIGN KEY (RELACAO_CLASSE_ID) REFERENCES RELACAO_CLASSE(RELACAO_CLASSE_ID),
FOREIGN KEY (TRAB_ID) REFERENCES TRABALHO_APLIC(TRAB_APLIC_ID),
FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO_APLIC(GRUPO_APLIC_ID),
FOREIGN KEY (TAR_ID) REFERENCES TAREFA_APLIC(TAR_APLIC_ID)
);

CREATE TABLE RELACAO_NOTAS (
RELACAO_NOTAS_ID SERIAL PRIMARY KEY,
GRUPO_ID INT NOT NULL,
USU_ID INT NOT NULL,
NOTA DOUBLE PRECISION,
PONTUACAO INT,
AVAL_POS_ID INT,
AVAL_NEG_ID INT,
AVAL_COMENT VARCHAR (250),
FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO_APLIC(GRUPO_APLIC_ID),
FOREIGN KEY (USU_ID) REFERENCES USUARIO_APLIC(USU_APLIC_ID),
FOREIGN KEY (AVAL_POS_ID) REFERENCES AVALIACAO_DESC(AVAL_ID),
FOREIGN KEY (AVAL_NEG_ID) REFERENCES AVALIACAO_DESC(AVAL_ID)
);

CREATE TABLE RELACAO_COMENT (
RELACAO_COMENT_ID SERIAL PRIMARY KEY,
TAR_TIPO CHAR NOT NULL,
COMENT_NUM INT NOT NULL,
USU_ID INT NOT NULL,
COMENT_DATE TIMESTAMP NOT NULL,
COMENT_DESC VARCHAR (400) NOT NULL,
FOREIGN KEY (USU_ID) REFERENCES USUARIO_APLIC(USU_APLIC_ID)
);

CREATE TABLE RELACAO_PERFIL (
RELACAO_PERFIL_ID SERIAL PRIMARY KEY,
UNI_ID INT,
USU_ID INT,
PERFIL_ID INT NOT NULL,
FOREIGN KEY (UNI_ID) REFERENCES UNIDADE_APLIC(UNI_APLIC_ID),
FOREIGN KEY (USU_ID) REFERENCES USUARIO_APLIC(USU_APLIC_ID),
FOREIGN KEY (PERFIL_ID) REFERENCES PERFIL_DESC(PERFIL_ID)
);

CREATE TABLE INDICACOES (
IND_ID SERIAL PRIMARY KEY,
ID_INDICADOR INT NOT NULL,
ID_INDICADO INT NOT NULL
);
-------------------VIEWS-------------------

CREATE VIEW VIEW_PONTUACAO AS
 SELECT usuario_aplic.usu_aplic_id AS usu_id,
    sum(relacao_notas.pontuacao) AS soma_pontos,
    count(*) AS qtd_avaliacoes,
    round(avg(relacao_notas.pontuacao), 2) AS media_pontuacao
   FROM usuario_aplic
     JOIN relacao_notas ON usuario_aplic.usu_aplic_id = relacao_notas.usu_id
  GROUP BY usuario_aplic.usu_aplic_id;

-------------------CARGAS-------------------

INSERT INTO STATUS_TAREFA_DESC VALUES ('1','PLANEJAMENTO');
INSERT INTO STATUS_TAREFA_DESC VALUES ('2','EM TRABALHO');
INSERT INTO STATUS_TAREFA_DESC VALUES ('3','ENTREGUE');
INSERT INTO STATUS_TAREFA_DESC VALUES ('4','CANCELADO');
COMMIT;

INSERT INTO COD_TIPO_DESC VALUES ('S','Rec. Senha');
INSERT INTO COD_TIPO_DESC VALUES ('4','Lib. Acesso');
COMMIT;

INSERT INTO LIB_SIGLAS_DESC VALUES ('A','Libera Admnistrador');
INSERT INTO LIB_SIGLAS_DESC VALUES ('S','Libera Secretário');
INSERT INTO LIB_SIGLAS_DESC VALUES ('F','Libera Financeiro');
INSERT INTO LIB_SIGLAS_DESC VALUES ('P','Libera Professor');
INSERT INTO LIB_SIGLAS_DESC VALUES ('E','Libera Estudante');
COMMIT;

INSERT INTO LIB_SIGLAS_DESC VALUES ('A','Libera Admnistrador');
INSERT INTO LIB_SIGLAS_DESC VALUES ('S','Libera Secretário');
INSERT INTO LIB_SIGLAS_DESC VALUES ('F','Libera Financeiro');
INSERT INTO LIB_SIGLAS_DESC VALUES ('P','Libera Professor');
INSERT INTO LIB_SIGLAS_DESC VALUES ('E','Libera Estudante');
COMMIT;

INSERT INTO PERFIL_DESC VALUES ('1','ROLE_AL','ALUNO');
INSERT INTO PERFIL_DESC VALUES ('2','ROLE_PR','PROFESSOR');
INSERT INTO PERFIL_DESC VALUES ('3','ROLE_SE','SECRETÁRIO');
INSERT INTO PERFIL_DESC VALUES ('4','ROLE_FI','FINANCEIRO');
INSERT INTO PERFIL_DESC VALUES ('5','ROLE_AD','ADMINISTRADOR');
INSERT INTO PERFIL_DESC VALUES ('6','ROLE_ES','ESCOLA');
COMMIT;

---------------------------- FIM -----------------------------




